apiVersion: v1
data:
  APP_DB: appdb
  APP_DB_OWNER: appowner
  APP_DB_RO_USER: backupuser
  APP_DB_USER: appuser
  APP_ENVIRONMENT: development
  CSRF_SIGNING_SECRET: your-csrf-signing-secret-CHANGE_ME!
  DEVELOPMENT_BASE_URL: http://localhost:8000
  DEVELOPMENT_DATABASE_URL: postgresql://appuser:devpass@localhost:5433/appdb
  DEVELOPMENT_REDIS_URL: redis://localhost:6380/0
  DEVELOPMENT_TEMPORAL_URL: localhost:7234
  FLY_APP_NAME: your-fly-app-name
  FLY_IO_API_KEY: your-fly-io-api-key
  FLY_ORG: your-fly-organization
  FLY_REGION: iad
  JWT_AUDIENCE: api://default
  JWT_AUDIENCE_SECONDARY: http://localhost:8000
  OIDC_GOOGLE_CLIENT_SECRET: your-google-client-secret
  OIDC_KEYCLOAK_CLIENT_SECRET: test-client-secret
  OIDC_MICROSOFT_CLIENT_SECRET: your-microsoft-client-secret
  OIDC_REDIRECT_URI: http://localhost:8000/auth/web/callback
  PRODUCTION_BASE_URL: http://localhost:8000
  PRODUCTION_DATABASE_URL: postgresql://appuser@postgres:5432/appdb
  PRODUCTION_REDIS_URL: redis://redis:6379/0
  PRODUCTION_TEMPORAL_URL: temporal:7233
  SESSION_MAX_AGE: "3600"
  SESSION_SIGNING_SECRET: your-session-signing-secret-CHANGE_ME!
  TEMPORAL_DB: temporal
  TEMPORAL_DB_USER: temporaluser
  TEMPORAL_VIS_DB: temporal_visibility
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: app-env
  name: env
